setup firebase sdk, pom.xml and test code to write to db
sps-2020-summer/GroupBuySPS2020 pull request #5
Opened 2020-07-12 11:37 UTC by leafgecko

2020-07-12 11:56 UTC, EugeneTeu commented on my-app/ServiceAccountKey.json
> +{
need to remove from version control as discussed

2020-07-13 08:31 UTC, pohlinwei reviewed
Is there a reason for pushing the .class files? 😅

2020-07-13 12:35 UTC, EugeneTeu requested changes
remove the api key plox

2020-07-13 17:20 UTC, leafgecko commented
> Is there a reason for pushing the .class files?

Oh that was auto generated as part of maven i believe, should we delete those or leave it there?

2020-07-16 14:05 UTC, EugeneTeu approved these changes

2020-07-18 01:28 UTC, pohlinwei approved these changes

2020-07-19 04:41 UTC, merged